export enum ROUTES {
    ROOT = '/',
    FAQ = '/faq',
    ABOUT = '/about',
    BLOG = '/blog',
    DOCS = '/docs',
    PRIVACYPOLICY = '/privacy_policy',
    TERMSofSERVICE = '/terms_of_service',
    AUTHENTICATEanITEM = '/authenticate_an_item',
    CUSTOMERCARE='/customer_care',
    HOWtoSHOP = '/how_to_shop',
    PRODUCTINFO= '/product_information',
    PAYMENT= '/payment',
    DELIVERY = '/delivery',
    RETURNS = '/returns',
}