export enum ROUTES {
    ROOT = '/',
    FAQ = '/faq',
    ABOUT = '/about',
    BLOG = '/blog',
    DOCS = '/docs',
    SIGNIN = '/sign_in',
    INSTALLMETAMASK = '/create_account',
    BUY = '/buy',
    NEWADRESS = '/new_delivery_address',
    PRIVACYPOLICY = '/privacy_policy',
    TERMSofSERVICE = '/terms_of_service',
    AUTHENTICATEanITEM = '/authenticate_an_item',
    CUSTOMERCARE='/customer_care',
    HOWtoSHOP = '/customer_care/how_to_shop',
    PRODUCTINFO= '/customer_care/product_information',
    PAYMENT= '/customer_care/payment',
    DELIVERY = '/customer_care/delivery',
    RETURNS = '/customer_care/returns',
}